[build]
publish = "public"
command = "yarn run build; zola build"

[build.environment]
ZOLA_VERSION = "0.16.1"

[context.deploy-preview]
command = "yarn run build; zola build --base-url $DEPLOY_PRIME_URL"
